Error if there are unmerged transitive dependencies
With this change, commit validation scripts using
alldependencies.py to checkout other linked projects will cause
the build to error if there are unmerged transitive dependencies.

This should make it easier to understand why a build might have
failed.

When this occurs it will output a message which looks as follows:

```
============================================
===       update all projects with       ===
===          the same Change-Id          ===
============================================
ERROR: Unmerged transitive dependencies:
ep-engine: refs/changes/90/60190/3
Fatal error - aborting
```

Change-Id: I1654dd123eeb8b4ed12bc7325152872783ba6676
Reviewed-on: http://review.couchbase.org/60698
Tested-by: Will Gardner <will.gardner@couchbase.com>
Reviewed-by: Volker Mische <volker.mische@gmail.com>
Reviewed-by: Dave Rigby <daver@couchbase.com>